-- Drop and recreate the bookings table
DROP TABLE IF EXISTS bookings CASCADE;

CREATE TABLE bookings (
    id bigint generated by default as identity primary key,
    project_id text unique not null,
    name text not null,
    email text not null,
    mobile text not null,
    service_selected text not null,
    additional_services text[] default '{}',
    requirements text not null,
    reference_urls text,
    reference_images text[] default '{}',
    progress float default 0,
    password text not null,
    status text default 'pending',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Recreate progress_notes table with proper references
DROP TABLE IF EXISTS progress_notes CASCADE;

CREATE TABLE progress_notes (
    id bigint generated by default as identity primary key,
    project_id text references bookings(project_id),
    note text not null,
    progress_value float not null,
    created_at timestamptz default now(),
    created_by text references admin_users(email)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_bookings_project_id ON bookings(project_id);
CREATE INDEX IF NOT EXISTS idx_bookings_email ON bookings(email);
CREATE INDEX IF NOT EXISTS idx_progress_notes_project_id ON progress_notes(project_id);
