-- Create project snapshots table
CREATE TABLE IF NOT EXISTS project_snapshots (
    id bigint generated by default as identity primary key,
    project_id text references bookings(project_id),
    image_url text not null,
    description text,
    created_at timestamptz default now(),
    created_by text references admin_users(email)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_snapshots_project_id ON project_snapshots(project_id);
